lrenie/wellbe

app/assets/stylesheets/config/_fonts.scss

J'ai importé les font dans le code

font importation done

---

app/models/exercise.rb

exercise , 4 presence true et name uniqueness

validates model exercise

---

app/controllers/sessions_controller.rb
app/models/session.rb
app/models/user.rb
config/routes.rb
db/seeds.rb

Validation de la seed avec création de données sur toutes les tables  ainsi que correction des bug dans les validations et les associations des models

Sees valide + correction dans les models

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_colors.scss
app/views/layouts/application.html.erb

J'ai créé les couleurs spécifiques au site : 
`$noir:` #08050B;
`$grisfonce:` #707070;
`$gris:` #BBBBBB;
`$grisclair:` #D0D0D0;
`$blanc:` #F5F4F6;
`$primary:` #B67CFF;
`$secondary:` #00DBD8;
J'ai set les h et p par default : 
`h1` {
font-size: 50.52px;
color: $noir;
}
`h2` {
font-size: 37.9px;
color: $noir;
}
`h3` {
font-size: 28.43px;
color: $noir;
}
`h4` {
font-size: 21.33px;
color: $noir;
}
`p` {
font-size: 16px;
color: $noir;
}

couleurs et h set

---

app/views/shared/_navbar-wellbe.html.erb
config/routes.rb

mis resources à la place de ressources

fix coquille route.rb

---

app/controllers/sessions_controller.rb
app/models/session.rb
app/views/sessions/choice.html.erb
db/migrate/20200826123917_change_favorite_status_table.rb
db/schema.rb
db/seeds.rb

Récupération des données pour implémenter la page "Choice" avec les dernières sessions et les favoris + enrichissement de la seed et changement de la colonne favorite_status pour la mettre dans la table session_participants

implémentation de la page choice avec récupération des données

---

app/assets/stylesheets/application.scss
app/views/pages/home.html.erb
app/views/shared/_card_multi_session.html.erb
app/views/shared/_card_solo_session.html.erb

bug bouton card session resolved

---

app/assets/stylesheets/components/_navbar.scss
app/views/pages/home.html.erb
app/views/sessions/new.html.erb
app/views/shared/_navbar_global.html.erb

Petite modif sur la navbar (gradiant)

mise à jour de la navbar global

---

app/models/body_area.rb
app/models/session.rb
db/seeds.rb

Seed mise à jour avec le body_area_id pour les sessions + associations implémentées dans les models

seed à jour ainsi que model

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_sessions_new.scss
app/javascript/controllers/index.js
app/javascript/controllers/radio_button_controller.js
app/javascript/packs/application.js
app/models/body_area.rb
app/models/session.rb
app/views/sessions/new.html.erb
app/views/shared/_card_body_area.html.erb
package.json
public/404.html
public/500.html
yarn.lock

J'ai réalisé la new de sessions (encore quelques modifs à faire mais utilisable)

new de session

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/views/sessions/new.html.erb
app/views/shared/_navbar_global.html.erb

navbar final

---

db/seeds.rb

create stat seed et lien user vers show user

modif seed et lien user

---

app/assets/stylesheets/pages/_user_index.scss
app/views/users/index.html.erb

Lien clickable

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_user_show.scss
app/views/shared/_navbar_global.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

navbar deco et z-index + show user avancé

---

app/controllers/application_controller.rb
app/helpers/meta_tags_helper.rb
app/views/layouts/application.html.erb
app/views/sessions/show.html.erb
config/initializers/default_meta.rb
config/meta.yml
db/seeds.rb

checkbox pour demoday mais pas fini

pas fini , want pull

---

app/controllers/session_participants_controller.rb
app/controllers/users_controller.rb
app/views/sessions/choice.html.erb
app/views/users/show.html.erb

update favorite session

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/views/users/show.html.erb

stat de la show de user

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_sessions_choice.scss
app/javascript/components/chrono.js

rcontent.com/59569740/92032248-29b0f280-ed6a-11ea-8738-f597c4f33888.png)

maj wording + calendar import css + ecrasement card choice

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_user_show.scss
app/controllers/users_controller.rb
app/views/shared/_card_multi_session.html.erb
app/views/shared/_card_prev_session_show_user.html.erb
app/views/shared/_card_solo_session.html.erb
app/views/users/show.html.erb
public/500.html

card et autre changement dans la showde user

---

app/controllers/sessions_controller.rb
app/models/friendship.rb
app/models/user.rb

affichage de tous les amis résolu

affichage de tous les amis résolu

---

app/assets/stylesheets/components/_card.scss
app/views/sessions/choice.html.erb
app/views/shared/_card_multi_session.html.erb
app/views/shared/_card_solo_session.html.erb

Choice final

---

app/helpers/application_helper.rb
app/views/shared/_card_prev_session.html.erb
app/views/shared/_card_prev_session_show_user.html.erb
app/views/users/show.html.erb

La date s'affiche correctement et en FRANCAIS

date en francais et bien affichées

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_user_index.scss
app/views/shared/_card_prev_session.html.erb
app/views/shared/_card_prev_session_show_user.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

paufinement final

---

app/views/shared/_pop_up_session.html.erb

Je joue les stats

---

app/views/shared/_navbar-wellbe.html.erb
app/views/shared/_navbar_global.html.erb

route des boutons navbar

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/users_controller.rb
app/views/shared/_navbar-wellbe.html.erb
app/views/shared/_navbar_global.html.erb
app/views/users/show.html.erb

petit changement

---

app/models/chat_participant.rb
app/models/chatroom.rb
app/models/message.rb
db/migrate/20200915180832_create_chatrooms.rb
db/migrate/20200915181103_create_chat_participants.rb
db/migrate/20200915181247_create_messages.rb
db/schema.rb
test/models/chat_participant_test.rb
test/models/chatroom_test.rb
test/models/message_test.rb

Création des modeles chatroom / Chat_participant / message

tables chatroom

---

app/javascript/controllers/show_sessions_controller.js

Mise en place de la méthode POST à la place d'un GET dans le fichier "show_sessions_controller" en JS afin de garantir la sécurité des données du User.

Methode POST pour Flatpickr

---

app/views/users/show.html.erb

dans la show de user , j ai ajouter 2 element fonctionnels en attente de marquage et de données

add 2 element into dashboard

---

app/views/users/show.html.erb

Espace pour les deux nouveaux elements operationnels en attentes de données

 cards ready

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_chatroom_index.scss
app/assets/stylesheets/pages/_chatroom_show.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/chatrooms_controller.rb
app/views/chatrooms/index.html.erb
app/views/chatrooms/show.html.erb

Index du chat quasiment fini
Show du chat quasiment fini aussi

front et back du chat

---

app/assets/stylesheets/pages/_chatroom_index.scss
app/assets/stylesheets/pages/_chatroom_show.scss
app/views/chatrooms/show.html.erb

jolie chat

---

app/javascript/channels/chatroom_channel.js
app/views/messages/_message.html.erb

AutoRefresh fonctionnel avec partial ok !

ActionCable fonctionnel

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_popup.scss
app/assets/stylesheets/pages/_chatroom_index.scss
app/assets/stylesheets/pages/_chatroom_show.scss
app/controllers/chat_participants_controller.rb
app/javascript/components/chatroom.js
app/javascript/components/create_chatroom.js
app/javascript/packs/application.js
app/views/chat_participants/_add_friends.html.erb
app/views/chatrooms/index.html.erb
app/views/chatrooms/show.html.erb
config/routes.rb

- Ajout d'un chat participant dans une chatroom existante
- Affichage dans le bon ordre des messages ainsi que de l'index des chatroom
- Custom scrollBar
- Custom modales

Action cable v3.2

---

app/controllers/session_exercises_controller.rb
app/controllers/sessions_controller.rb
app/javascript/components/create_chatroom.js
app/views/shared/_card_prev_session.html.erb
app/views/shared/_card_prev_session_show_user.html.erb
config/routes.rb

Implémentation de :
- debug de la choice avec condition correctement écrite pour affichage des prev sessions
- première version de l'algo de création des exercices

debug de la page choice + implémentation V1 de l'algo
